export enum TipoSolicitud {

  REGISTRO_ASIGNATURA='REGISTRO_ASIGNATURA',
  HOMOLOGACION='HOMOLOGACION',
  CANCELACION_ASIGNATURA='CANCELACION_ASIGNATURA',
  SOLICITUD_CUPO='SOLICITUD_CUPO',
  CONSULTA_ACADEMICA='CONSULTA_ACADEMICA',
}
